# Spring Boot Configuration for KhananSoft

server:
  port: 8080

    
spring:
  application:
    name: Vahan360
  
  # Data configuration
  data:
    mongodb:
      # MongoDB Atlas connection
      uri: mongodb+srv://admin_user:CCYqOxtIH3pH7EZj@cluster0.zixaxl3.mongodb.net/
      database: khanan_db
      # Connection pool settings
      auto-index-creation: true
      
  
